services:
  selenium-hub:
    image: selenium/hub:4.10.0
    environment:
      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    platform: linux/amd64
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.10.0
    platform: linux/amd64
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  firefox:
    image: selenium/node-firefox:4.10.0
    platform: linux/amd64
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  tests:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-hub
    environment:
      - BROWSER=chrome
      - SELENIUM_GRID_URL=http://selenium-hub:4444/wd/hub/

    restart: on-failure

  video:
    image: selenium/video:ffmpeg-4.3.1-20230912
    platform: linux/amd64
    container_name: selenium-video
    volumes:
      - ./videos:/videos
    depends_on:
      - selenium-hub
    environment:
      - DISPLAY_CONTAINER_NAME=chrome-node
      - FILE_NAME=execution.mp4

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
    volumes:
      - ${PWD}/target/allure-results:/app/allure-results
